### ISSUE TITLE
代码报错，求助

### ISSUE THREAD

**Issue by ROYZELIEN** [v3ucn/CosyVoice_For_Windows#11]
Traceback (most recent call last):
  File "C:\AI\CosyVoice\basic_usage.py", line 8, in <module>
    output = cosyvoice.inference_sft('你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？', '中文女')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\CosyVoice\cosyvoice\cli\cosyvoice.py", line 31, in wrapper
    result = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CosyVoice.inference_sft() missing 1 required positional argument: 'new_dropdown'

**Comment by v3ucn** [comment]
少了一个参数 new_dropdown ， 这个参数是webui我自己加的参数，用来加载自定义音色
