### ISSUE TITLE
安装时运行install deepspeed from https://github.com/S95Sedan/Deepspeed-Windows/releases/tag/v14.0%2Bpy311有错误

### ISSUE THREAD

**Issue by sinwo0O** [v3ucn/CosyVoice_For_Windows#2]
(cosyvoice) PS D:\Projects\CosyVoice_For_Windows> install deepspeed from https://github.com/S95Sedan/Deepspeed-Windows/releases/tag/v14.0%2Bpy311
install : 无法将“install”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ install deepspeed from https://github.com/S95Sedan/Deepspeed-Windows/ ...
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (install:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

(cosyvoice) PS D:\Projects\CosyVoice_For_Windows> pip install deepspeed from https://github.com/S95Sedan/Deepspeed-Windows/releases/tag/v14.0%2Bpy311
Collecting https://github.com/S95Sedan/Deepspeed-Windows/releases/tag/v14.0%2Bpy311
  Downloading https://github.com/S95Sedan/Deepspeed-Windows/releases/tag/v14.0%2Bpy311
     \ 169.5 kB 1.5 MB/s 0:00:00
  ERROR: Cannot unpack file C:\Users\shihx.ICKEY\AppData\Local\Temp\pip-unpack-jv4dinbg\v14.0+py311 (downloaded from C:\Users\shihx.ICKEY\AppData\Local\Temp\pip-req-build-i3bonh4e, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of C:\Users\shihx.ICKEY\AppData\Local\Temp\pip-req-build-i3bonh4e

请帮忙看看

**Comment by v3ucn** [comment]
这个不是命令，意思是去 https://github.com/S95Sedan/Deepspeed-Windows/releases/tag/v14.0%2Bpy311 这个网址下载whl安装文件，然后通过 pip install whl文件  来进行安装
