### ISSUE TITLE
这啥错误啊

### ISSUE THREAD

**Issue by sdrz001** [v3ucn/CosyVoice_For_Windows#24]
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:739 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

**Comment by zihaohi** [comment]
onnxruntime-gpu与CUDA版本不匹配，卸载onnxruntime-gpu装一个与CUDA匹配的版本就好了
pip uninstall onnxtime-gpu
