### ISSUE TITLE
这个TTS 是不是生成速度很慢

### ISSUE THREAD

**Issue by xtntrna** [v3ucn/CosyVoice_For_Windows#7]
# 开始计时
start_time = time.time()

# 生成语音
output = cosyvoice.inference_sft('你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？', '中文女', '无')

# 计算生成耗时
end_time = time.time()
generation_time = end_time - start_time
print(f"生成耗时: {generation_time:.2f} 秒")

结果是 3.69秒， 4090 24G 卡

**Comment by frasercai** [comment]
好像慢 4090 我测的也是这样，不知道是不是哪里姿势不对，流式也慢，超过10个字就都在3秒以上了

**Comment by sdrz001** [comment]
我的4060 10秒音频 需要20秒来生成 还在找原因
